jobs:
  - job: Lint

    pool:
      vmImage: ubuntu-latest

    steps:
      - template: ../steps/init-node.yml

      - script: npx run-s test:readme test:peer-deps lint test:ava test:check-type-defs-pkgs
        displayName: Run linter
        timeoutInMinutes: 5

    cancelTimeoutInMinutes: 1
