parameters:
  version: 8

steps:
  # - task: JavaToolInstaller@0
  #   inputs:
  #     versionSpec: ${{ parameters.version }}
  #     jdkSourceOption: AzureStorage
  #     azureResourceManagerEndpoint: myARMServiceConnection
  #     azureStorageAccountName: myAzureStorageAccountName
  #     azureContainerName: myAzureStorageContainerName
  #     azureCommonVirtualFile: jdk1.6.0_45.zip
  #     jdkDestinationDirectory: $(agent.toolsDirectory)/jdk
  #   displayName: Install Java

  - bash: |
      node -p 'Object.entries(process.env).filter(([key]) => /^java_home/i.test(key)).reduce((obj, [key, value]) => ({ ...obj, [key]: value }), {})'
    displayName: Show JAVA_HOME

  - bash: export JAVA_HOME="${JAVA_HOME_11_X64}"
    displayName: Set Java version to 11

  - script: java -version
    displayName: Show Java version
